### PR TITLE
Improved handling of assemblies with multiple versions

### LINKED ISSUE #77: Exception when Updating Step to new version of plugin
When you register a plugin assembly with a higher minor version you have to update (move) the steps from the old version of the plugin to the new version of the plugin.
When you go to update step and choose the new version of the plugin you get the following error:
image
After refreshing the tool the step is correctly updated to the correct plugin version.

Also, it would be nice to show the assembly version like `(Plugin v1.0.0.0) Plugin Name` and `(Plugin v1.1.0.0) Plugin Name` when there are two versions of the same plugin registered in the system because currently, you need to guess the correct plugin as you see the same plugin twice:
image

### PR DESCRIPTION
**Pull request by BetimBeja**
Fixes #77

### CODE REVIEW

**Comment by BetimBeja** [comment]
@imranakram do you think someone can review this PR?

**Comment by BetimBeja** [comment]
@rappen can you find someone who review this, please?

**Comment by BetimBeja** [comment]
I changed the position of the version information so that there is an improved readability of the node names by moving the version to the end of the name so that different versions of plugins are next to each other on the combobox and the tree view.
image

**Comment by imranakram** [comment]
Thanks for the PR and sorry for the delay, it's now published in the latest release :)

**Pull request merged**
